### ISSUE TITLE
Coloring PCA plot points by metadata

### ISSUE THREAD

**Issue by jwill490** [reneshbedre/bioinfokit#1]
Hi there,

Is there anyway to color the points in the PCA plots by a metadata attribute without forking the project? For example, I have 4 sample types (fetal12w, fetal13w, adult12w, adult13w) across 29 samples. I'd like the samples to be color-coded by these groups if at all possible.

Thanks!
John

**Comment by reneshbedre** [comment]
Hi John

To answer your questions, I would like to see the data that you would like to PCA plot. As I understood, you have 20 samples and the observations are of four types (fetal12w, fetal13w, adult12w, adult13w). Is it right? If possible, please email me data at reneshbe@gmail.com

**Comment by mbaddoo** [comment]
Hello-
First, this is a great tool!  Thanks so much for the documentation.  Like jwill490, I too am interested in coloring points in the PCA plots by a metadata attribute.  I have 24 samples, 8 observations.  I appreciate any assistance you could offer. 
Thanks again!
Melody
[DEG_hg38.csv](https://github.com/reneshbedre/bioinfokit/files/6786518/DEG_hg38.csv)
