### ISSUE TITLE
Consider uploading to bioconda

### ISSUE THREAD

**Issue by claymcleod** [reneshbedre/bioinfokit#11]
Really great library! Thanks for making it—it's saved me quite a bit of time.

I'm using this to perform tpm conversion in a Jupyter notebook. My entire environment can be installed with a `conda install` with the exception of this tool. Please consider [adding it as a bioconda recipe](https://bioconda.github.io/contributor/index.html).

**Comment by reneshbedre** [comment]
@claymcleod 

I have added the `bioinfokit` package to bioconda. You can install it using bioconda as,

`conda create -n env-name bioinfokit`

Let me know if you still have any issues. Thank you for your recommendation.
