### ISSUE TITLE
Labeling most significant/highest log fold change?

### ISSUE THREAD

**Issue by theclairecamp** [reneshbedre/bioinfokit#14]
I was wondering if it is possible to label the values that are above a certain p-value and logfoldchange threshold with in the genenames parameter, instead of having to change the threshold within lfc_thr and pv_thr? Like by using indexes for tubles?
Thanks!

**Comment by reneshbedre** [comment]
Hi @theclairecamp ,

If you set `genenames='deg' ` , it will label all the points of up and down-regulated genes as defined by your threshold `lfc_thr` and `pv_thr`. See documentation at https://reneshbedre.github.io/blog/howtoinstall.html#volcano-plot

Let me know if it resolves your issue. Thank you for using bioinfokit for your work.
