### ISSUE TITLE
Change angle of gene name labels so they don't overlap

### ISSUE THREAD

**Issue by theclairecamp** [reneshbedre/bioinfokit#15]
I see there is a command to change the axis rotation but the labels for the gene names some times overlap, is it possible to change their orientation?
Thanks!
<img width="459" alt="Screen Shot 2020-09-18 at 1 53 09 PM" src="https://user-images.githubusercontent.com/34284555/93644164-4a0dbd80-f9b6-11ea-817a-1d6db993728b.png">

**Comment by reneshbedre** [comment]
@theclairecamp 

Yes, if the gene points are very close to each other, the labels will most likely overlap. For now, there is no other way around. But, it is under development to make not label to overlap in volcano and other scatter plots. Thank you for your suggestion.
