### ISSUE TITLE
No so many modules within the installed latest version bioinfokit

### ISSUE THREAD

**Issue by bei-lab** [reneshbedre/bioinfokit#16]
Hi,
   Bioinfokit is real a good tool to manage the common next-generation sequencing issues. It seems a bug that there are no so many modules within the installed latest version, or it may be my problem?

`>>>` import bioinfokit

`>>>` bioinfokit.__version__
'0.9.8'
`>>>` dir(bioinfokit)
['__author__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'name']
`>>>` dir(bioinfokit.name)
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']"

**Comment by reneshbedre** [comment]
Hi @bei-lab 

Thank you for your input. I do not think there is any problem. Do you encounter any issue while running bioinfokit?
