### ISSUE TITLE
manhatten plot y axis tick labels

### ISSUE THREAD

**Issue by sabrinacamp2** [reneshbedre/bioinfokit#17]
Hi!

Thank you for this amazing suite of tools. It has made making a manhatten plot a breeze! 

I am having some trouble getting my Y-axis tick labels to look right, and I thought maybe you would have some advice. First, I did not specify the `ylm` argument and looked at the default labeling. There is a lot of number overlap, so then I tried setting the axis limits and intervals with the `ylm` argument to `ylm = (0, 35, 3)`. It still isn't quite right and I would love your input. 

All the best,
Sabrina 
![default_params_manhatten](https://user-images.githubusercontent.com/52207849/94866919-37f83a00-040e-11eb-9d7f-43267f43f0c7.png)
![manhatten](https://user-images.githubusercontent.com/52207849/94866936-3d558480-040e-11eb-9b38-2679f51afdb8.png)

**Comment by reneshbedre** [comment]
@sabrinacamp2 

Thank you for your feedback about bioinfokit and I am glad that it is useful in your work. Regarding your query, can you please tell me what is the lowest p-value in your dataset? Is it possible for you to share your dataset at reneshbe@gmail.com?

**Comment by sabrinacamp2** [comment]
Hi!

The lowest p-value in my dataset is 4.940656e-324. I unfortunately cannot share this dataset.

All the best,
Sabrina

**Comment by reneshbedre** [comment]
@sabrinacamp2 

Thank you for providing the information. You have the lowest p-value 4.940656e-324 which becomes 323.30 on minus log10 scale. Please, provide option as `ylm=(0, 330, 30)`. You can change it as it fits your need. Let me know if it works for you.

**Comment by sabrinacamp2** [comment]
This worked! Thank you for your quick and helpful response. 

Sabrina 
![edited_y_brcavsgnomad](https://user-images.githubusercontent.com/52207849/94938326-ae447d00-049e-11eb-9096-80ad29e34892.png)
