### ISSUE TITLE
read csv

### ISSUE THREAD

**Issue by kyawwh** [reneshbedre/bioinfokit#18]
How can i read my own csv file?

**Comment by reneshbedre** [comment]
@kyawwh 
check this out https://reneshbedre.github.io/blog/pandas.html#import-data-from-file

**Comment by kyawwh** [comment]
Thank you, sir.
But I can't calculate my csv file in t-test.   It show 'res column is not in data frame.![IMG_20201013_132226.jpg](https://user-images.githubusercontent.com/71485832/95815205-326dee80-0d42-11eb-9206-4fe7e2cd3dc3.jpg)

Can you explain me, some code to calcluate in my data csv file for t-test?

**Comment by kyawwh** [comment]
Thank you. Sir

**Comment by reneshbedre** [comment]
Did you solve your issue?

**Comment by kyawwh** [comment]
Yes. But I can't use t test(type3, paired t test) . There is error in paired ttest.

**Comment by reneshbedre** [comment]
Can you please send error details?

**Comment by kyawwh** [comment]
![IMG_20201014_162859.jpg](https://user-images.githubusercontent.com/71485832/95957320-94535480-0e25-11eb-8f81-c3f63487dad9.jpg)
This is my dataframe.

**Comment by kyawwh** [comment]
![IMG_20201014_162911.jpg](https://user-images.githubusercontent.com/71485832/95957390-ac2ad880-0e25-11eb-8532-3b98ede250ad.jpg)
This is error show me.

**Comment by kyawwh** [comment]
![IMG_20201014_164018.jpg](https://user-images.githubusercontent.com/71485832/95958436-24de6480-0e27-11eb-9bdf-4102a7c1993c.jpg)

This is my data frame.

![IMG_20201014_164029.jpg](https://user-images.githubusercontent.com/71485832/95958470-30ca2680-0e27-11eb-9912-d92f5a6dd345.jpg)

This is error.

Can you tell me, how can I sent you message from github?

**Comment by reneshbedre** [comment]
@kyawwh 

You need to keep only `Ewt` and `Twt` in the dataframe.  You can do that like this way

`df = df[['Ewt', 'Twt']]`

Then again run the `ttest` on this updated dataframe.

Let me know if you still have trouble. You can also send me an email at reneshbe@gmail.com

**Comment by kyawwh** [comment]
![IMG_20201015_173840.jpg](https://user-images.githubusercontent.com/71485832/96098663-62f78900-0ef8-11eb-980b-7514d8740569.jpg)![IMG_20201015_173903.jpg](https://user-images.githubusercontent.com/71485832/96098670-64c14c80-0ef8-11eb-98bd-0e29c66ea2e2.jpg)

There is still problem sir.

**Comment by kyawwh** [comment]
![IMG_20201015_174314.jpg](https://user-images.githubusercontent.com/71485832/96099236-08126180-0ef9-11eb-997d-a1a81ea4fda2.jpg)


There is still problem sir.

**Comment by reneshbedre** [comment]
@kyawwh 

You have saved the dataframe in the `y` variable.

Update your code as `res.ttest(df=y, res=['Twt', 'Ewt'], test_type=3)`

**Comment by kyawwh** [comment]
Sorry, sir. Yesterday, I uploaded 2 pic, but one was uploaded. ![IMG_20201015_174325.jpg](https://user-images.githubusercontent.com/71485832/96206018-f6c76480-0f8d-11eb-9aa5-962275bbd475.jpg)
This is another pic. I tried y variable. But, still error.

**Comment by reneshbedre** [comment]
@kyawwh 

Follow the docs carefully https://reneshbedre.github.io/blog/ttest.html#paired-t-test-dependent-t-test

You need to import the `stat` class as `from bioinfokit.analys import stat` and then run the test again with correct dataframe

**Comment by kyawwh** [comment]
Thank you
