### ISSUE TITLE
What the df in the Normalization part

### ISSUE THREAD

**Issue by susutBu** [reneshbedre/bioinfokit#19]
Hello Dr. Bedre,
Thanks for you developed this tool for bioinformatic analysis, it useful do much.
When I caculate the CPM, RPKM or TPM, there a question confused me. You mentioned the df is `Pandas dataframe containing raw gene expression values`, How can I understand the `expression values` ? It is the mapping counts or any other number? if it is anyother number, how do you generate it?
Thanks

**Comment by reneshbedre** [comment]
Hi @susutBu 

Thank you for your feedback about bioinfokit. The expression values that I mentioned in the [post ](https://reneshbedre.github.io/blog/expression_units.html#-gene-expression-units-and-calculation-) are the raw reads counts obtained by mapping RNA-seq reads to the genome.
