### ISSUE TITLE
No images

### ISSUE THREAD

**Issue by Qianjiang-Github** [reneshbedre/bioinfokit#2]
Dear all,
When I draw a volcano plot using visuz.volcano(), there is no image or error report appear.
Does anyone know what is the problem here?
Thank you!

![image](https://user-images.githubusercontent.com/53710108/77351341-ed4e8480-6d3d-11ea-94c8-70d6caa34a0b.png)

**Comment by reneshbedre** [comment]
Hi,
I have reproduced the code and it is working fine. The image will not appear on the Jupyter console, but it will be saved in the same folder from where you are executing the code. You can check your current folder path using `pwd` command on Jupyter. Check the image (volcano.png) in that folder.
Let me know if you still have problems.

**Comment by Qianjiang-Github** [comment]
Dear @reneshbedre,
Thank you so much! I get the figures with your help.
However, I would like to ask is it possible that display in the Jupyter console?
Thanks!

**Comment by reneshbedre** [comment]
Hi,
Thank you for your suggestion. Currently, it does not support the feature of viewing the graph in the console itself. I will consider adding this feature in the upcoming release.

**Comment by Qianjiang-Github** [comment]
That is great!
Thanks a lot!

**Comment by reneshbedre** [comment]
The viewing of the graph in the console itself is supported in v0.5. Please install v0.5 and set `show=True` to view the graph in the console itself.

**Comment by Qianjiang-Github** [comment]
Thanks!!!
