### ISSUE TITLE
Help Request: why the max value of Tukey Test is 0.9

### ISSUE THREAD

**Issue by Yiyiyimu** [reneshbedre/bioinfokit#21]
Thanks for the awesome work @reneshbedre !

My question is, as shown in [the working example of tukey test](https://www.reneshbedre.com/blog/anova.html#multiple-pairwise-comparisons-post-hoc-test), we could find the max value of p-value is 0.9, while I think it should be 1.0. Do you know the reason for it?

---

Or maybe I should ask, why is that the p-value got from [`psturng`](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/stats/libqsturng/qsturng_.py#L845) is from 0.001 to 0.9, but not 1.0

**Comment by reneshbedre** [comment]
@Yiyiyimu 

This is a good question. The p values obtained by  `psturng` are bound between 0.001 and 0.9 based on the degree of freedoms. If you get a p-value of 0.001, you should interpret it as <=0.001. As per the documentation, `psturng` uses scalar minimization to get the p values and they are bound between .001 and .9.

Source: https://github.com/statsmodels/statsmodels/blob/master/statsmodels/stats/libqsturng/qsturng_.py
https://code.google.com/archive/p/qsturng-py/

**Comment by Yiyiyimu** [comment]
@reneshbedre Thanks for the reference for algorithm explanation of `psturng`! I get it, Gleason's table only have data between 0.1 and 0.999, so the p values we get are from .001 to .9.

It seems R's implementation of tukey test would reach 1.0, I'll take a look at that.

Thanks again!
