### ISSUE TITLE
Normalization on TCGA dataset

### ISSUE THREAD

**Issue by vappiah** [reneshbedre/bioinfokit#23]
Hello bioinfokit team, I have downloaded raw htseq gene expression data from TCGA and I would like to perform FPKM normalization. But on checking the documentation the commands require the gene lengths but I don't have that info. Is there a way to normalize without supplying the gene length? Thanks

**Comment by reneshbedre** [comment]
@vappiah 
FPKM is based on the gene length for normalization. Check formula [here](https://www.reneshbedre.com/blog/expression_units.html#rpkm-reads-per-kilo-base-per-million-mapped-reads). If you do not have gene length you can use CPM or DESeq2 for normalization. Check [here](https://www.reneshbedre.com/blog/expression_units.html#rpm-or-cpm-reads-per-million-mapped-reads-or-counts-per-million-mapped-reads-).

**Comment by vappiah** [comment]
Thanks @reneshbedre I will do that
