### ISSUE TITLE
Manhattan plot with fst 

### ISSUE THREAD

**Issue by vappiah** [reneshbedre/bioinfokit#24]
Hello developers,

I would like to know if its advisable to use bioinfokit to make manhattan plot on my data which has chromosome(in the format Pf3D7_{1-13}_v3), position and fst values.

Thanks

**Comment by vappiah** [comment]
Hi @reneshbedre  I was able to modify the manhattan plot codes to work with Fixative Index(FST) values . I tried on a Plasmodium falciparum snp data and it worked perfectly. I can send you the script . It might be work to consider that in the bioinfokit package.

**Comment by reneshbedre** [comment]
@vappiah 

Thank you for your update on the Manhatten plot with Fst values. Currently, `mhat` function in bioinfokit takes p values and transforms to the log scale for plotting the Manhatten plot. 

I am glad that you found the way around. Yes, sure, you can send me the code and if possible. the subset of the data. You can send me on email reneshbe@gmail.com. Thank you for your input.

**Comment by reneshbedre** [comment]
@vappiah 

I have added the support for Fst values in the Manhattan plot. See [this page](https://www.reneshbedre.com/blog/manhattan-plot.html) for updated documentation. Let me know if you have further questions.
