### ISSUE TITLE
FASTQ batch downloads from SRA database not working for Windows

### ISSUE THREAD

**Issue by DeevanshuGoyal** [reneshbedre/bioinfokit#25]
Hi,

It seems that the command "bioinfokit.analys.fastq.sra_bd" doesn't work for Windows. The issue seems to be the absence of fasterq function in the Windows version of the SRA toolkit. 

Is there any other way to use this function or be able to download large batches of data from the SRA database in a single command?

Regards.

**Comment by reneshbedre** [comment]
@DeevanshuGoyal ,

`bioinfokit.analys.fastq.sra_bd` does not work on Windows. You should use it on Mac or Linux OS. You need to have the NCBI SRA toolkit installed and should be in the system path.
