### ISSUE TITLE
Saving Plots in High Resolution

### ISSUE THREAD

**Issue by vappiah** [reneshbedre/bioinfokit#27]
Hi @reneshbedre . I would like to suggest an additional parameter for saving the images and that is to include dpi option so that plots can be saved as high resolution images.

**Comment by reneshbedre** [comment]
@vappiah 

Thank you for your suggestion. The DPI parameter for setting the resolution is already included and can be defined with parameter `r`. Please see docs here https://github.com/reneshbedre/bioinfokit

**Comment by vappiah** [comment]
I found it . Thanks
