### ISSUE TITLE
Multiple plot windows

### ISSUE THREAD

**Issue by vappiah** [reneshbedre/bioinfokit#29]
Hi @reneshbedre I was trying to use bioinfokit to generate heatmaps for gene expression data following your example [here](https://www.reneshbedre.com/blog/heatmap-python.html). Whenever I use show =True, multiple windows are opened which just one of them displaying the heatmap. Please advice

**Comment by reneshbedre** [comment]
@vappiah 

I think this issue is associated with the seaborn package
