### ISSUE TITLE
issue importing analys & visuz

### ISSUE THREAD

**Issue by catch-minie** [reneshbedre/bioinfokit#3]
HI , I am facing following 2 errors while using bioinfokit:

1. While using it via linux cmd line , all dependencies are installed, still facing following error:
Python 3.8.2 (default, Apr 17 2020, 12:53:23) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bioinfokit
>>> from bioinfokit import analys, visuz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'analys' from 'bioinfokit' (unknown location)
>>> from bioinfokit import analys
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'analys' from 'bioinfokit' (unknown location)
>>> from bioinfokit import visuz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'visuz' from 'bioinfokit' (unknown location)

2.While using this library bioinfokit via jupyter notebook I am unable to generate the plots.

any help  regarding what could be the reason why  I am facing these issues shall be vry
helpful.

**Comment by reneshbedre** [comment]
**For your first question**, can you please tell me how did you install the bioinfokit?
Meantime, please try to install using a virtual environment (make sure you are running python 3.8.2)

`python -m venv venv382`
`source venv382/bin/activate`
`pip install bioinfokit`

After successful installation, try importing under python interpreter again like `from bioinfokit import analys, visuz`

Let me know if you still face the same problems

**For your second question:**
The image will not appear on the Jupyter console, but it will be saved in the same folder from where you are executing the code. You can check your current folder path using `pwd` command on Jupyter.

To view the graph in the console itself set parameter `show=True` (supported in v0.5 or later) 

Please, read docs for more details https://reneshbedre.github.io/blog/howtoinstall.html

**Comment by catch-minie** [comment]
Thanks for you prompt reply.
I am able to generate plots in jupyter however I am still facing problem in linux  enviornment, following is the error, after running first two command mentioned by you ,this is the third command followed by error:
pip install bioinfokit
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting bioinfokit
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/bioinfokit/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/bioinfokit/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/bioinfokit/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/bioinfokit/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/bioinfokit/
  Could not fetch URL https://pypi.org/simple/bioinfokit/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/bioinfokit/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  ERROR: Could not find a version that satisfies the requirement bioinfokit (from versions: none)
ERROR: No matching distribution found for bioinfokit
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
(venv382) admin1@admin1-PowerEdge-T630:~/bioinfokit$ python3
Python 3.8.2 (default, Apr 17 2020, 12:53:23) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

**Comment by reneshbedre** [comment]
It looks like you are having an issue with connection to PyPI
Check this post https://github.com/pypa/pip/issues/5448 for possible solutions
