### ISSUE TITLE
coloring points in PCA plots

### ISSUE THREAD

**Issue by mbaddoo** [reneshbedre/bioinfokit#32]
Hello-
First, this is a great tool! Thanks so much for the documentation. Like jwill490 who commented Nov 2020, I too am interested in coloring points in the PCA plots by a metadata attribute. I have 24 samples, 8 observations. I appreciate any assistance you could offer.
Thanks again!
Melody
[DEG_hg38.csv](https://github.com/reneshbedre/bioinfokit/files/6786542/DEG_hg38.csv)

**Comment by reneshbedre** [comment]
If you have target variable information for all observations, you can color the points on PCA plot or biplot. See here for example, https://www.reneshbedre.com/blog/principal-component-analysis.html#principal-component-analysis-pca-with-a-target-variable
