### ISSUE TITLE
error with saving figure with figname

### ISSUE THREAD

**Issue by justinesjw** [reneshbedre/bioinfokit#33]
Hi Renesh,

Thanks for building this package. 

I'm struggling with altering the file name using the parameter figname.

![image](https://user-images.githubusercontent.com/26448066/126120097-4ecf6b6d-21dd-4af1-b5e3-83bd32df47a5.png)

Please advise.

Thanks,
Justine

**Comment by reneshbedre** [comment]
@justinesjw which version of bioinfokit you are using? Please update to the latest one and try again. https://www.reneshbedre.com/blog/install-upgrade-pip-windows-mac-linux.html#upgrading-installed-python-packages-to-the-latest-version
