### ISSUE TITLE
TypeError: hmap() got an unexpected keyword argument 'rowclus'

### ISSUE THREAD

**Issue by archana433** [reneshbedre/bioinfokit#5]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-ad0a6225036a> in <module>()
      2 df = df.set_index(df.columns[0])
      3 df.head()
----> 4 visuz.gene_exp.hmap(df=np.log2(df), cmap='RdYlBu', dim=(5, 10), tickfont=(8, 4),clus=False,rowclus=True)

TypeError: hmap() got an unexpected keyword argument 'rowclus'

**Comment by reneshbedre** [comment]
Hi,

I think you are using an old version of bioinfokit. The `rowclus` parameter introduced in v0.8.4. Please, update bioinfokit to the latest version. See details https://reneshbedre.github.io/blog/howtoinstall.html#heatmap

How you can update it?
pip install --upgrade bioinfokit 

for other ways check here https://reneshbedre.github.io/blog/howtoinstall.html#how-to-install
