### ISSUE TITLE
It is possible to create a volcano plot without significant genes?

### ISSUE THREAD

**Issue by diitaz93** [reneshbedre/bioinfokit#50]
Hi!
I have read through #22, #31 and #39 which are similar, as they show the error `AssertionError: either significant or non-significant genes are missing; try to change lfc_thr or pv_thr to include both significant and non-significant genes`, but I can't find a way to plot a volcano plot when there are no significant genes. I am using these plots as an exploratory analysis of several datasets and it would be very useful for me to see cases where there are no significant genes.

Thanks!

**Comment by reneshbedre** [comment]
Yes, it could be possible. Change the threshold of log fold change and p values just to make a few genes at a significant level (based on your criteria). You can also keep the same color using a color parameter.
