### ISSUE TITLE
Axis limits cannot be NaN or Inf

### ISSUE THREAD

**Issue by mbaddoo** [reneshbedre/bioinfokit#52]
Greetings Renesh-
I echo other users when I say that this is a great tool!  Thank you very much.  I am attempting to generate a Manhattan plot, but am met with the message  "Axis limits cannot be NaN or Inf.  My smallest p-value is 4.9E-323.  Might you offer some advice on how to overcome the error, please?
Thank you-
Melody

**Comment by reneshbedre** [comment]
The low p-value should not be a problem. I think you have NaN value on either of the axis. Can you please check your dataset? If you would like, you can also share, so that I can take a look.
