### ISSUE TITLE
assertion error for non-significant genes in lfc

### ISSUE THREAD

**Issue by lraghavendran** [reneshbedre/bioinfokit#55]
Is it possible to turn off the assertion check for the presence of non-significant genes. I have some datasets for which I do not see any down-regulated genes at all. I can't create a volcano plot due to this
AssertionError: either significant or non-significant genes are missing; try to change lfc_thr or pv_thr to include both significant and non-significant genes

**Comment by reneshbedre** [comment]
Change the threshold of log fold change and p values just to make a few genes at a significant level (based on your criteria). You can also keep the same color using a color parameter.
