### ISSUE TITLE
Manhattan Plot Highlighting

### ISSUE THREAD

**Issue by rmandla** [reneshbedre/bioinfokit#6]
Hi, 

Thanks for making this! We need more python tools for analyzing genomic data. 

Is it possible to highlight specific points in a Manhattan plot different colors (i.e. SNPs occuring in an exon are blue, SNPs in an intron are green....)?

**Comment by reneshbedre** [comment]
Hi @rmandla ,

Thank you for your suggestions and comments. For now, bioinfokit does not support the Manhatten plot for coloring SNPs based on genetic features. I will consider it to add in future releases.
