### ISSUE TITLE
How to properly adjust figure size and y axis label size 

### ISSUE THREAD

**Issue by Aynur31** [reneshbedre/bioinfokit#8]
Hello Dr. Bedre,
First, thank you very much for the simple and useful heat map code. 
I am new to this field and trying to find my way. Your source has been very helpful to me. 
Here IS the heatmap I made from FPKM values, from cuffdiff. then zPFKM and used this matrix for heatmap. I changed dim and tickfont to have a better figure but still could get one.
My question is that maybe I need to have fewer gene lists to show on the y-axis? or otherwise, How do I make it legible?
I have 229 gene lists and if I can show all of them on the label, that would be great. 
![heatmap](https://user-images.githubusercontent.com/68058339/89779795-d0fa8b00-db18-11ea-8691-2831f636d54d.png)

**Comment by reneshbedre** [comment]
Hi @Aynur31,

Thank you for using bioinfokit. It would be difficult to display all 229 genes on the heatmap unless you increase the height and lower the font size. But, this may not be convenient for publication purposes. You can play with `dim` and `tickfont ` parameters to get a better heatmap. But still, you could not get as you wanted, remove the gene names from the heatmap, or create multiple heatmaps based on the gene functional categories.
